#======================================================================================================================#
# CMAKE BUILD SYSTEM
#======================================================================================================================#
#
#----------------------------------------------------------------------------------------------------------------------#
CMAKE_MINIMUM_REQUIRED(VERSION 3.12...3.18)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# Project Information
#----------------------------------------------------------------------------------------------------------------------#
PROJECT(MAIN)
ENABLE_LANGUAGE(C)
ENABLE_LANGUAGE(CXX)
ENABLE_LANGUAGE(Fortran)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# INSTALL PREFIX
#----------------------------------------------------------------------------------------------------------------------#
SET(MAIN_PREFIX_ROOT "~/bin/${CMAKE_PROJECT_NAME}")
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# CMake verbosity
#----------------------------------------------------------------------------------------------------------------------#
SET(CMAKE_VERBOSE_MAKEFILE OFF)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# Cmake output of compile commands during generation
#----------------------------------------------------------------------------------------------------------------------#
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# Include other configurations
#----------------------------------------------------------------------------------------------------------------------#
SET(CMAKE_MODULE_PATH "${MAIN_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH})
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# User defined variables
#----------------------------------------------------------------------------------------------------------------------#
INCLUDE(DefineOptions)
INCLUDE(DefineMacros)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# Output Folders
#----------------------------------------------------------------------------------------------------------------------#
INCLUDE(DefineOutputFolders)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# Build Type
#----------------------------------------------------------------------------------------------------------------------#
INCLUDE(DefineBuildType)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# Compiler Flags
#----------------------------------------------------------------------------------------------------------------------#
INCLUDE(CompilerFlagsGNU)
INCLUDE(CompilerFlagsINTEL)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# EXTERNAL LIBRARIES
#----------------------------------------------------------------------------------------------------------------------#
INCLUDE(ConfigureHDF5)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# Adding Libraries
#----------------------------------------------------------------------------------------------------------------------#
INCLUDE_DIRECTORIES(src)
#----------------------------------------------------------------------------------------------------------------------#
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/globals/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/lib-data-export/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/lib-data-import/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/lib-geometry/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/lib-mesh/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/lib-utilities/configfiles-tools/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/lib-utilities/data-structures/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/lib-utilities/hdf5-tools/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/lib-utilities/numerics-tools/)
ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/src/main/)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# Build MAIN-PREPROCESSOR
#----------------------------------------------------------------------------------------------------------------------#
INCLUDE(BuildMainMeshRefinementForIBM)
#----------------------------------------------------------------------------------------------------------------------#
