#----------------------------------------------------------------------------------------------------------------------#
# PROJECT NAME
#----------------------------------------------------------------------------------------------------------------------#
ProjectName = "MDA30P30N"
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# PREPROCESSING METHOD
#----------------------------------------------------------------------------------------------------------------------#
NGeo = 1
MeshDimension = 3
#----------------------------------------------------------------------------------------------------------------------#
WhichMeshConstructionMethod = "mesh-import"
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# MESH REFINEMENT AROUND GEOMETRY
#----------------------------------------------------------------------------------------------------------------------#
InputGeometryFolder     = "./ini/geometries"
InputGeometryFile       = "mda30p30n-flap.stl"
InputGeometryFileFormat = "stl"
DebugGeometryImport     = .FALSE.
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# MESH IMPORT
#----------------------------------------------------------------------------------------------------------------------#
InputMeshFolder     = "./ini/meshes"
InputMeshFile       = "mda30p30n-wing-slat.msh"
InputMeshFileFormat = "gmsh"
DebugMeshImport     = .FALSE.
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# MESH ROTATION
#----------------------------------------------------------------------------------------------------------------------#
RotateMesh = .FALSE.
RotationAngle3D = (/90.0,0.0,0.0/)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# BOUNDARY CONDITIONS
#----------------------------------------------------------------------------------------------------------------------#
BoundaryMark = 1
BoundaryName = "FarField"
BoundaryMark = 2
BoundaryName = "SymmetryPlane"
BoundaryMark = 3
BoundaryName = "Wing"
BoundaryMark = 4
BoundaryName = "Slat"
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# MESH REFINEMENT
#----------------------------------------------------------------------------------------------------------------------#
DebugMeshRefinement = .FALSE.
DebugMeshElementsList = .FALSE.
#----------------------------------------------------------------------------------------------------------------------#
WhichMeshRefinement = "refine-elements-around-geometry-and-inside-box"
#----------------------------------------------------------------------------------------------------------------------#
WhichBoxedRegion = "adaptive-box"
#----------------------------------------------------------------------------------------------------------------------#
WhichBodyGeometry = "imported-geometry"
#----------------------------------------------------------------------------------------------------------------------#
WhichGeometryDistribution = "stl-facets-distribution"
#----------------------------------------------------------------------------------------------------------------------#
TessellationMaxEdgeLength = 1.0E-02
ElementEnlargementFactor  = 10.0
RegionEnlargementFactor   = 0.1
#----------------------------------------------------------------------------------------------------------------------#
MaxRefinementLevel = 3
#----------------------------------------------------------------------------------------------------------------------#
IsotropicRefinement  = .FALSE.
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# EXPORT MESH PARAMETERS
#----------------------------------------------------------------------------------------------------------------------#
ExportMesh  = .TRUE.
#----------------------------------------------------------------------------------------------------------------------#
MeshExportFormat = "hdf5-coda"
MeshExportFormat = "tecplot-ascii"
MeshExportFormat = "gmsh"
#----------------------------------------------------------------------------------------------------------------------#
